Repository rafamatoso/unifbv-portalead, pull requests merged in 2020-04, with the labels that each got.

#4 feature: login com layout basico para testes
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/assets/img/gery-wibowo-Eti6ph51H4A-unsplash.jpg
  frontend/src/assets/img/index.js
  frontend/src/components/MaterialUi/Copyritgh/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
Labels: dependencies, enhancement

#5 Adicionado o firebase
  frontend/.env.example
  frontend/.gitignore
  frontend/package.json
  frontend/src/services/firebase.js
Labels: dependencies

#6 Feature/fe/tela painel
  frontend/src/components/NavBar/index.js
  frontend/src/components/NavBar/styles.js
  frontend/src/pages/Login/index.js
  frontend/src/routes/index.js
Labels: enhancement

#8 feature: add custom loading progress component
  frontend/src/components/CustomButton/index.js
  frontend/src/components/CustomLoader/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/styles.js
Labels: enhancement

#9 Feature/fe/add contextapi firebaseauth
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Login/styles.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Home/Register/styles.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/Login/index.js
  frontend/src/routes/index.js
  frontend/src/services/Firebase/firebase.js
  frontend/src/services/Firebase/index.js
Labels: chore, feature

#10 Tela de adicionar aula concluida
  frontend/package.json
  frontend/src/components/ProgressBar/index.js
  frontend/src/pages/AddVideo/helper.js
  frontend/src/pages/AddVideo/index.js
  frontend/src/pages/AddVideo/styles.js
  frontend/src/routes/index.js
Labels: dependencies, feature

#12 Feature/fe/add localstorage
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Copyritgh/index.js
  frontend/src/components/CustomButton/index.js
  frontend/src/components/CustomProgressBar/index.js
  frontend/src/components/NavBar/index.js
  frontend/src/components/ProgressBar/index.js
  frontend/src/components/index.js
  frontend/src/pages/AddVideo/ModalUpload/index.js
  frontend/src/pages/AddVideo/index.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/Perfil/index.js
  frontend/src/pages/Perfil/styles.js
  frontend/src/pages/index.js
  frontend/src/routes/index.js
  frontend/src/routes/routeWrapper.js
  frontend/src/serviceWorker.js
  frontend/src/services/Firebase/index.js
  frontend/src/services/firebase/config.js
  frontend/src/services/firebase/index.js
  frontend/src/services/storage/index.js
  frontend/src/services/storage/storageKeys.js
  frontend/src/store/index.js
  frontend/src/store/types.js
  frontend/src/utils/colors.js
  frontend/src/utils/strings.js
Labels: chore, feature

#14 Feature/fe/add home register
  frontend/src/components/CustomLoader/index.js
  frontend/src/components/index.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Login/styles.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Home/Register/styles.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/Perfil/index.js
  frontend/src/pages/index.js
  frontend/src/routes/routeWrapper.js
  frontend/src/services/firebase/index.js
  frontend/src/utils/strings.js
Labels: chore, feature

#15 Feature/fe/add backdrop loading
  frontend/src/assets/img/index.js
  frontend/src/pages/AddCourse/index.js
  frontend/src/pages/AddCourse/styles.js
  frontend/src/pages/CriarCurso/index.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/index.js
  frontend/src/routes/index.js
  frontend/src/services/firebase/index.js
  frontend/src/store/index.js
  frontend/src/store/types.js
  node_modules/.yarn-integrity
Labels: feature

#16 feature: add validations with in inputs field
  frontend/src/pages/AddVideo/index.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Login/styles.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Home/Register/styles.js
  frontend/src/pages/Home/helper.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
Labels: chore, feature

#18 feature: adjusts in navbar component
  frontend/src/components/NavBar/index.js
  frontend/src/components/NavBar/styles.js
  frontend/src/components/index.js
  frontend/src/pages/Perfil/index.js
  frontend/src/pages/Perfil/styles.js
  frontend/src/utils/strings.js
Labels: chore, feature

#17 Feature/fe/list courses
  frontend/src/components/CardCourse/index.js
  frontend/src/components/CardCourse/styles.js
  frontend/src/components/NavBar/index.js
  frontend/src/components/index.js
  frontend/src/pages/Course/AddCourse/index.js
  frontend/src/pages/Course/AddCourse/styles.js
  frontend/src/pages/Course/ListCourse/index.js
  frontend/src/pages/Course/ListCourse/styles.js
  frontend/src/pages/CriarCurso/index.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Perfil/index.js
  frontend/src/pages/Perfil/styles.js
  frontend/src/pages/Video/AddVideo/ModalUpload/index.js
  frontend/src/pages/Video/AddVideo/helper.js
  frontend/src/pages/Video/AddVideo/index.js
  frontend/src/pages/Video/AddVideo/styles.js
  frontend/src/pages/index.js
  frontend/src/routes/index.js
  frontend/src/services/firebase/signs.js
Labels: feature

#19 chore: improve code quality for all project
  README.md
  backend/.env.example
  backend/.gitignore
  backend/package.json
  backend/src/app.js
  backend/src/controllers/.gitkeep
  backend/src/routes.js
  backend/src/server.js
  frontend/src/App.js
  frontend/src/assets/img/index.js
  frontend/src/components/CardCourse/index.js
  frontend/src/components/CardCourse/styles.js
  frontend/src/components/Copyritgh/index.js
  frontend/src/components/CustomButton/index.js
  frontend/src/components/CustomProgressBar/index.js
  frontend/src/components/NavBar/index.js
  frontend/src/components/NavBar/styles.js
  frontend/src/components/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Course/AddCourse/index.js
  frontend/src/pages/Course/AddCourse/styles.js
  frontend/src/pages/Course/ListCourse/index.js
  frontend/src/pages/Course/ListCourse/styles.js
  frontend/src/pages/Home/Login/index.js
  frontend/src/pages/Home/Login/styles.js
  frontend/src/pages/Home/Register/index.js
  frontend/src/pages/Home/Register/styles.js
  frontend/src/pages/Home/helper.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/styles.js
  frontend/src/pages/Video/AddVideo/ModalUpload/index.js
  frontend/src/pages/Video/AddVideo/index.js
  frontend/src/pages/index.js
  frontend/src/routes/index.js
  frontend/src/routes/routeWrapper.js
  frontend/src/serviceWorker.js
  frontend/src/services/firebase/config.js
  frontend/src/services/firebase/signs.js
  frontend/src/services/storage/index.js
  frontend/src/services/storage/storageKeys.js
  frontend/src/store/index.js
  frontend/src/store/types.js
  frontend/src/utils/colors.js
  frontend/src/utils/strings.js
  node_modules/.yarn-integrity
Labels: chore, documentation

#20 Chore/fe/improve code quality
  README.md
  frontend/src/index.js
  frontend/src/pages/Video/AddVideo/index.js
  frontend/src/serviceWorker.js
  frontend/src/services/firebase/signs.js
  frontend/src/services/storage/index.js
Labels: chore, documentation

#22 chore: adjusts in documentation
  README.md
Labels: chore, documentation

#23 chore: fix error in code quality badge
  README.md
Labels: chore, documentation

#29 Feature/fe/list video
  frontend/package.json
  frontend/src/components/CardCourse/index.js
  frontend/src/components/NavBar/index.js
  frontend/src/components/NavBar/styles.js
  frontend/src/pages/Course/AddCourse/index.js
  frontend/src/pages/Course/ListCourse/index.js
  frontend/src/pages/Course/ListCourse/styles.js
  frontend/src/pages/Video/AddVideo/helper.js
  frontend/src/pages/Video/AddVideo/index.js
  frontend/src/pages/Video/ListVideo/index.js
  frontend/src/pages/Video/ListVideo/styles.js
  frontend/src/pages/index.js
  frontend/src/routes/index.js
  frontend/src/routes/routeWrapper.js
  frontend/src/services/firebase/Models/Course.js
  frontend/src/services/firebase/Models/Video.js
  frontend/src/services/firebase/Models/index.js
  frontend/src/utils/collections.js
Labels: chore, dependencies, feature

#30 Bug router
  frontend/src/pages/Video/ListVideo/index.js
  frontend/src/routes/routeWrapper.js
  frontend/src/services/firebase/Models/Video.js
Labels: bug
